name: Build APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Verificar arquivos
      run: |
        ls -la
        if [ ! -f buildozer.spec ]; then
          echo "ERRO: buildozer.spec não encontrado na raiz!"
          exit 1
        fi

    - name: Compilar APK
      run: |
        buildozer android debug

    - name: Enviar APK
      uses: actions/upload-artifact@v3
      with:
        name: Xihundla-APK
        path: bin/*.apk
